### ISSUE TITLE
`[#A/B/C]` priority icons get ignored when placing the cursor for edit position

### ISSUE THREAD

**Issue by artjomsR** [femto-code/logseq-one-theme#2]
Hello! Thank you for making this theme, loving it! I've noticed a small issue. For context, I do my task planning in a separate Planner file, which is structured like this
```
- TODO [#A]
	- do thing
- TODO [#B]
	- do thing2
- TODO [#C]
	- do thing3
```

So when I need to add a new entry, I simply click on the respective `TODO [#A]`, `TODO [#B]` or `TODO [#C]`, the cursor is automatically placed at the end, and then I can press `Enter` to create a new child.

With the `One Theme`, the priority icons seem to get ignored for this and the cursor is being placed between the TODO and the priority text, i.e.: `TODO I [#A]` and not `TODO [#A] I`. This now requires an extra click/key press to go to the end of the line before pressing `Enter` would create a new child.

Would be super grateful for your time 🙏 

https://github.com/femto-code/logseq-one-theme/assets/6875790/c6acdfa0-b6b0-4341-93ff-b4a624bcf841

**Comment by femto-code** [comment]
Hi @artjomsR ! Thanks very much for your feedback and for reporting your issue!

First, let me ask you to give some more details about your setup. What Logseq version are you running?
From your screen recording I can see that you are using some custom CSS markup. This might be relevant for this issue, so feel free to post that as well. It might be interesting especially because I cannot reproduce the problem on my system 🙈 (tho I have not tried it on Windows yet, will do that asap). On my machine, the cursor gets set correctly AFTER the priority text (as you expected it).

Highly appreciate your request!

**Comment by femto-code** [comment]
Trying the same on Windows, I couldn't reproduce the issue. Let me know, how you customized your Logseq. Pretty sure there is a reasonable explanation.

**Comment by artjomsR** [comment]
Hello, thank you for getting back to me, appreciate it! I've actually thought of a quick workaround by manually writing the priority after the TODO, e.g. `TODO [#A] A` and it even looks better on the todo plugin as a result :) 
![image](https://github.com/femto-code/logseq-one-theme/assets/6875790/67182d2e-1f52-4fb1-aeab-dadb84abae30)

Since I'm happy with the workaround, and you can't reproduce this, I propose to close it for now. If somebody gets this in the future, they can reopen the issue and I can help out with testing if needed.
